# Site settings
title:             Dhavauzan Official Website
email:             sionmikhaelefraim@gmail.com
description:       Seputar info profil dan contact dari Dhavauzan as Webtoon Creator of Bloody Fake Smile .
author:            Mikhro
baseurl:           ""
url:               "http://dhav-af.github.io"

